### ISSUE TITLE
Small fix on the documentation (general information)

### ISSUE THREAD

**Issue by jonquet** [ontoportal/administration#2]
1. Links
Section:
https://ontoportal.github.io/administration/
contains links in next sentence encoded a certain way: 
"The OntoPortal Virtual Appliance is provided by the Stanford Center for Biomedical Informatics Research and the OntoPortal Alliance. " (Not working).

Where as Section:
https://ontoportal.github.io/administration/general/introduction/
the same links are encoded differently (working).

2. Versions
I assume the versions here need to be updated: 
https://ontoportal.github.io/administration/general/system_requirements/#image-format-and-operating-system-details

3. Licensing
In section: https://ontoportal.github.io/administration/general/licensing/
Texts says "who wish to deploy" incitating to request a License BEFORE asking for an Appliance. Where as for registration of a new License, an Appliance ID is required. More details come in next sub-sections though. Maybe just rephrase to reader to quit the page now.
In the same section 
License certificates are obtained at the [OntoPortal License Server](https://license.ontoportal.org]. 
Not working link.

4. Details
- AllegoGraph is written on Frantz website with capital G, need to be changed throughout the all documentation. 
- https://ontoportal.github.io/administration/general/architecture_reference/#architectural-overview diagram might require a refresh ;)
- https://ontoportal.github.io/administration/general/architecture_reference/#architectural-overview
We would expect this doc becoming the place to document future release, so I would suggest to remove 2nd sentence and store subsequent info (after 3.0) here.

5. General
- Focus to essential info. Avoid repetition from one section to the other. 
- Decide if the NCBO wiki (at least sections related to VA) will go away and if not, build the new doc atop of it avoiding repetition (e.g., releases, old requirements)

**Comment by graybeal** [comment]
1) Is working now; the encodings seem to resolve fine to actual titles. No hyperlinks exist in that sentence.
2) Yes, versions now updated
3) Licensing:
  a) I *think* this is OK, partly I reworded and partly I think it's OK to put in your request without the Appliance ID. Details to be confirmed.
  b) Should be OK but haven't confirmed yet.
4) Nits:
  a) Fixed. Yay for global replace.
  b) Oh yeah. :-) Really just a placeholder.
  c) @jonquet  I think the link here is wrong, can you point to where you think future releases should go?
5) General
  a) Well, yes. Specific improvements are easiest after pointers to the offending bits.
  b) The decision was consciously made, sorry (but not shocked) if it isn't already clear. 
     (i) To my knowledge there is nothing in the NCBO wiki about the administration of the VA that has not been transferred. 
     (ii) On the other hand, almost nothing about _operations_ in the NCBO wiki *is* transferred (the main exception being bits about loading ontologies)—that will be a separate document at a future time, perhaps with the help of the Alliance.

**Comment by jonquet** [comment]
Point 2 ok .

Point 4c. Indeed the URL was: 
https://ontoportal.github.io/administration/general/history/#release-histories
I modify to remove the 2nd sentence to keep the reader on this web page and not send him out to old wiki.  But I assume the link back to old wiki is because the "OntoPortal Virtual Appliance Release Notes" page is not ready. 
Maybe to avoid creating too much page (keep it simple) the page "History of the Virtual Appliance" can be rename "OntoPortal Virtual Appliance Release Notes" and future release notes and history of versions will be stored here. 

Point 5 ok. 
I would then archive the wiki pages or clearly mentioned on top in red the link to new documentation web site.

**Comment by syphax-bouazzouni** [comment]
@jonquet  is this still relevant? (either way please close)

**Comment by jonquet** [comment]
I will close this for now. Will wait for new revision of the documentation after new doc is ready.
